default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: task4_itr_development
  username: root
  password: "1542sasha"
  host: localhost

development:
  <<: *default
  database: task4_itr_development

test:
  <<: *default
  database: task4_itr_test


production:
  adapter: postgresql
  database: task4_itr_production
  username: task4_itr
  password: <%= ENV['TASK4_ITR_DATABASE_PASSWORD'] %>
